### ISSUE TITLE
Redirect or show custom message for users who are trying to enter a restricted public group

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-restrictions#2]
When a group is restricted to certain users but is "public" users who are not allowed to join the group can still view all the content. For some communities this might be the right behaviour (you can view a group you just can't contribute to the discussion) but for CFCommunity I'd like to do the following:

When a user who does not have the correct member type tries to visit a public restricted group we could do the following

1: Redirect to the group directory and show them an alert  "Sorry the group you tried to enter is only viewable for _member type_"

2: Redirect to a custom page set through a plugin option.

I think option 2 would be a bit more flexible because you have some space to explain the why and how. We'll probably need a few basic plugin options anyway to let people decide on these things.

**Comment by imath** [comment]
Ok i'll deal with this one tonight, just cloned @henrywright 's great work and will commit when it's fixed

**Comment by BoweFrankema** [comment]
Awesome!
