### ISSUE TITLE
Show additional information on group privacy selection based on Restriction

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-restrictions#3]
So there is one thing we would have to explain to our users.

Just because a group is restricted to a certain member type to view/join it does not mean that by default everything you post is PRIVATE. 

So it would be smart to add some additional information. For example

[ v  ] Public + Restricted to _Member Type_
Your group can only be joined and viewed by others who have CF. All the activity inside your group (forum topics, updates and such) remains public. This means that other people on our community can still see content in this group appear through the newsfeed and profiles of their friends!

Choose this Group Privacy if: You want to create a group where only people with CF can post, but it's not a problem when other people who do not have CF see it somewhere on CFCommunity!

[ v  ] Private + Restricted _Member Type_
Your group can only be joined and viewed by others who have CF. Also all the content that is posted in this group stays inside this group and will not be viewable anywhere else on our community.

Choose this Group Privacy if: You want to create a group where only people with CF can post and keep all the content private inside this group.

It would probably make the most sense to show this with javascript as well once a user chooses to select a group restriction!

**Comment by imath** [comment]
it looks like @henrywright made the good decision here :)

He chose checkbox inputs to let group creators/admins select the member type. I think it can be made by dynamically adding the message when a member type is selected. I'll make a suggestion in my commit.

**Comment by BoweFrankema** [comment]
Yep!
