### ISSUE TITLE
Allow Group Restrictions to be changed on the Group Admin screen?

### ISSUE THREAD

**Issue by BoweFrankema** [CFCommunity-net/buddypress-group-restrictions#4]
Do we want to give a group admin the ability to change the group restrictions after creating a group? Currently this has not been added to the Group Admin screen, but I think it would make sense to do so (since it's also possible to change group privacy). 

I looked at available hooks but could not find them, so maybe we should resort to javascript once again. We could enqueue conditionally just based on being in the group admin to save a http request and potential conflicts (which Henry is already doing beautifully ;-)

**Comment by imath** [comment]
Absolutely! it will be fixed when i'll commit.
